transport:
  require_tls: true

permit_list:
  recipients:
    - dr.smith@hospital.org
    - oncology-team@hospital.org

policy:
  actions:
    insecure_transport: "BLOCK"
    contains_phi_not_permitted: "REDACT"
    otherwise: "ALLOW"

logging:
  level: "INFO"
  format: "%(asctime)s %(levelname)s %(name)s - %(message)s"
